apiVersion: v1
clusters:
- name: "capi-cloud"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EWXdNakE0TXpnd05sb1hEVE0xTURZd01qQTRNemd3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlVsClRyWHZZVytYTnBqaG94enZ1MHg4MVRiVUZQZWNpK2xsRkZEL2p5MjdyZkVmR0gwbDB0UkpDV2tveGpUWFMzUVcKTWdveXlWUXFkYVNmN1lEVGNvanRLeGZIdGNHZUlydDRoMXVZSFFzUDZ2MzRrUUdrbDNkdW03VFhvazBkTE83Tgo4aDRYRnQxWEJabEtWQUJzaEE5WGIwMjZhbnArcGNIby9vM05lay84SXBBbHkrKy8zUnVxbkwwWldyakt4cWNICmlLcFNnTmhSVWVTS05nQ21KNEtWbUpnaE5Ia3NIZUkvMGd1d050aEh4TjZHV2hnVlVnTnlQQXdDakFkWlhJNEcKKzBhd3lSTURCbVlFeXRZMVNYd1lOZFFrYWZFZllkWk1CN01FMDNMRDJNTXVlelJSaXY1TmgwVU9nUGp3VTl1OQo5bldhTHRPczdSSFNBeUh1RzBzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEZ1lYU1JIZUVEVWhucmdVZlVNTFhmbVVBYzVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDV2RoSlNFcWNhdjJ3ZFppUFhLMEpqOExmVEFxcWZ3eDFCMkNqVVdxbmZtNTB4bHIyUQpGQmpwUTF2cDkvakZiTXlvV2pRNkRHbUR2ZCtiY3lqa2lWL1M4YmxtaHF5Nlc4RkpoWlVzZVJYMUlTV3JkUEhqCncxSkJ2SFRXSmxIeFM0dGxJTEh6ejRkU3dieGVySXdtbEpPUHBubXRXU2pFRFNzYVNPZy94ZjY0L3ZuQy94bTUKTUEzOFZtZFk1WnE1QWwwa1NEUWZNR0hiODdWTm9rZHU5cUs5NE1zWDBxUzk3YkVoMG1GaUhIaU9SNHEwUUZRUwp6R0RuTW1yaHhtekd0SmZuRGJFamNhekx0bkRpOHB0NzRYK1ZxRFEwUGhCQlh3d0RzcU5GVldFVno1ZWZrcWNxCjBQdG9iZ0lDTzNOWHdwOWhDd0VpZnBzQkQ2WUl5WUFGblRxMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://e9eee436-e30b-4f3c-9968-e7c3d5a0c5c5.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@capi-cloud
  context:
    cluster: "capi-cloud"
    user: capi-cloud-admin
current-context: admin@capi-cloud
kind: Config
preferences: {}
users:
- name: capi-cloud-admin
  user:
    token: CuF51BTh2CPAZbFHWmkKxSYEqb9AGn17IVmHVNY4V2dmgciEtLH3C0Fh