# Certificate for azure.ocho.ninja
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azure-ocho-ninja-tls
  namespace: default
spec:
  secretName: azure-ocho-ninja-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - rocket-app.azure.ocho.ninja
  # Set the certificate to renew 30 days before expiry
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days