apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-app
  labels:
    app: rocket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocket-app
  template:
    metadata:
      labels:
        app: rocket-app
    spec:
      containers:
      - name: rocket-app
        image: rg.fr-par.scw.cloud/ammi-ns/rocket:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: KUBERNETES_VERSION
            value: "1.30.0"
          - name: SCW_PROJECT_ID
            value: "f4b6faa9-0dce-4b18-8f99-824118e7d857"
          - name: SCW_REGION
            value: "fr-par"
          - name: SPECIAL_LEVEL_KEY
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: CLIENT_ID
          - name: SPECIAL_TYPE_KEY
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: CLIENT_SECRET
          - name: SCW_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: scwsm-secret
                key: secret-access-key
          - name: SCW_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: scwsm-secret
                key: access-key