apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret
    namespace: default
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: azure-credentials
        creationPolicy: Owner
    data:
      - secretKey: CLIENT_ID
        remoteRef:
          key: id:064700af-c6da-4bee-9bf1-81647ec8376b
          version: latest_enabled
      - secretKey: CLIENT_SECRET
        remoteRef:
          key: id:d533c135-a07d-4343-b2b4-286c5b6a3a23
          version: latest_enabled