apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-cloud
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://your-frontend-domain"
spec:
  tls:
    - hosts:
        - rocket-app.azure.ocho.ninja
      secretName: azure-ocho-ninja-tls
  rules:
  - host: rocket-app.azure.ocho.ninja
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocket-front
            port:
              number: 3000
