apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Uncomment and modify this section if you need to set image tags dynamically
# images:
# - name: ${DOCKER_REGISTRY}/rocket-app
#   newName: your-registry/rocket-app
#   newTag: latest

# Uncomment and modify this section if you need to add environment-specific configurations
# configMapGenerator:
# - name: rocket-app-config
#   literals:
#   - ENV_VAR_1=value1
#   - ENV_VAR_2=value2